# Generated by Django 4.2.16 on 2025-07-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='mrad',
            field=models.FloatField(max_length=100),
        ),
    ]
